-- ============================================================================
-- Perdidos Algures — schema.sql
-- ----------------------------------------------------------------------------
-- Reconstrução da base Supabase para documentação e reprodução.
--
-- Exatos (do dump da base): a extensão, TODAS as funções (RPCs) e TODAS as
--   políticas RLS.
-- Reconstruídas (inferidas do uso nas funções + dump de colunas da `sessions`):
--   as definições CREATE TABLE. Os nomes e tipos de coluna vêm do código das
--   funções; constraints/índices podem diferir ligeiramente da base viva. Para
--   exatidão total, compara com information_schema.columns da tua base.
--
-- Corre numa base VAZIA para recriar o essencial. Numa base já existente, os
-- CREATE ... IF NOT EXISTS não sobrescrevem nada; as funções (CREATE OR REPLACE)
-- e as políticas sim.
-- ============================================================================

-- ── Extensões ────────────────────────────────────────────────────────────────
-- gen_random_bytes (tokens de sessão) vive no schema `extensions`. É por isso
-- que as funções a referem como extensions.gen_random_bytes — com search_path
-- 'public', a forma sem prefixo NÃO é encontrada (foi a causa do bug do login).
create extension if not exists pgcrypto with schema extensions;

-- ── Tabelas (reconstruídas — ver nota no topo) ───────────────────────────────
create table if not exists public.profiles (
  id           uuid primary key default gen_random_uuid(),
  name         text not null,
  display_name text,
  initials     text,
  color        text default '#8b6f47',
  photo_url    text,
  is_admin     boolean not null default false
);

create table if not exists public.profiles_auth (
  profile_id   uuid primary key references public.profiles(id) on delete cascade,
  pass_hash    text not null,
  must_change  boolean not null default false,
  temp_expires timestamptz,
  updated_at   timestamptz default now()
);

-- Colunas confirmadas a partir do dump real da base.
create table if not exists public.sessions (
  token      text primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  last_seen  timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '90 days')
);

create table if not exists public.editions (
  id            uuid primary key default gen_random_uuid(),
  number        integer default 0,
  title         text,
  subtitle      text,
  status        text default 'active',
  current_phase integer default 1,
  data          jsonb default '{}'::jsonb,
  updated_at    timestamptz default now()
);

create table if not exists public.chat_messages (
  id         bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  text       text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.bug_reports (
  id          uuid primary key default gen_random_uuid(),
  by_id       text,
  by_name     text,
  description text not null,
  image       text,
  created_at  timestamptz not null default now()
);

-- ── RLS: ativar em todas as tabelas ──────────────────────────────────────────
alter table public.profiles      enable row level security;
alter table public.profiles_auth enable row level security;  -- sem políticas = só via funções SECURITY DEFINER
alter table public.sessions      enable row level security;
alter table public.editions      enable row level security;
alter table public.chat_messages enable row level security;
alter table public.bug_reports   enable row level security;  -- sem políticas = só via funções

-- ── Políticas (exatas, do dump) ──────────────────────────────────────────────
-- Leituras abertas; escritas passam pelas RPCs com token. `profiles_auth` e
-- `bug_reports` não têm políticas de propósito (acesso só via funções).
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to public using (true);

drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert on public.profiles for insert to public with check (true);

drop policy if exists editions_select on public.editions;
create policy editions_select on public.editions for select to public using (true);

drop policy if exists chat_select on public.chat_messages;
create policy chat_select on public.chat_messages for select to public using (true);

-- A `sessions` é interna: dentro das funções SECURITY DEFINER current_user é o
-- dono (postgres); numa chamada direta do browser é 'anon' → bloqueado.
drop policy if exists sessions_definer_only on public.sessions;
create policy sessions_definer_only on public.sessions for all to public
  using      (current_user <> all (array['anon'::name, 'authenticated'::name]))
  with check (current_user <> all (array['anon'::name, 'authenticated'::name]));

-- ── Triggers de apoio ────────────────────────────────────────────────────────
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Impede criar/escalar contas admin a partir da app.
create or replace function public.profiles_guard_admin()
returns trigger language plpgsql security definer set search_path to 'public' as $$
begin
  if tg_op = 'INSERT' then
    if coalesce(new.is_admin, false) then
      raise exception 'nao e permitido criar contas admin a partir da app';
    end if;
  elsif tg_op = 'UPDATE' then
    if coalesce(new.is_admin, false) is distinct from coalesce(old.is_admin, false) then
      raise exception 'nao e permitido alterar o estatuto de admin a partir da app';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_guard_admin_trg on public.profiles;
create trigger profiles_guard_admin_trg
  before insert or update on public.profiles
  for each row execute function public.profiles_guard_admin();

-- Trigger opcional (Supabase Auth). A app usa auth próprio (profiles_auth), por
-- isso normalmente não dispara; incluído por completude.
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path to 'public' as $$
declare uname text;
begin
  uname := coalesce(new.raw_user_meta_data->>'name', split_part(new.email,'@',1));
  insert into public.profiles (id, name, initials, color, photo_url, is_admin)
  values (
    new.id, uname,
    coalesce(new.raw_user_meta_data->>'initials', upper(left(uname, 1))),
    coalesce(new.raw_user_meta_data->>'color', '#8b6f47'),
    new.raw_user_meta_data->>'photo_url',
    lower(split_part(new.email,'@',1)) = 'miguel'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

-- ── Helpers de sessão / permissões ───────────────────────────────────────────
create or replace function public.session_owner(p_token text)
returns uuid language plpgsql security definer set search_path to 'public' as $$
declare uid uuid;
begin
  if p_token is null or length(p_token) < 20 then return null; end if;
  select profile_id into uid from public.sessions
   where token = p_token and expires_at > now();
  if uid is not null then
    update public.sessions set last_seen = now() where token = p_token;
  end if;
  return uid;
end $$;

create or replace function public.session_valid(p_token text)
returns boolean language sql security definer set search_path to 'public' as $$
  select exists (select 1 from public.sessions
                  where token = p_token and expires_at > now())
$$;

create or replace function public.is_admin(p_profile_id uuid)
returns boolean language sql security definer set search_path to 'public' as $$
  select coalesce((select is_admin from public.profiles where id = p_profile_id), false)
$$;

create or replace function public._edition_can_write(p_uid uuid, p_field text)
returns boolean language sql immutable as $$
  select p_field in ('rsvp','avail','locVotes','accVotes','locSuggs','accSuggs',
                     'planData','tieVotesLoc','tieVotesAcc')
$$;

-- ── Autenticação (com o fix do gen_random_bytes aplicado) ────────────────────
create or replace function public.auth_login2(p_profile_id uuid, p_hash text)
returns jsonb language plpgsql security definer set search_path to 'public' as $$
declare tok text; rec record;
begin
  perform pg_sleep(0.4);
  select pass_hash, must_change, temp_expires into rec
    from public.profiles_auth where profile_id = p_profile_id;
  if rec.pass_hash is null or rec.pass_hash <> p_hash then
    return jsonb_build_object('ok', false);
  end if;
  if rec.must_change and rec.temp_expires is not null and rec.temp_expires < now() then
    return jsonb_build_object('ok', false, 'expired', true);
  end if;

  delete from public.sessions
   where profile_id = p_profile_id
     and token not in (select token from public.sessions
                        where profile_id = p_profile_id order by last_seen desc limit 4);
  tok := encode(extensions.gen_random_bytes(32), 'hex');
  insert into public.sessions(token, profile_id) values (tok, p_profile_id);
  return jsonb_build_object('ok', true, 'token', tok, 'must_change', coalesce(rec.must_change, false));
end $$;

create or replace function public.auth_login(p_profile_id uuid, p_hash text)
returns text language plpgsql security definer set search_path to 'public' as $$
declare tok text;
begin
  perform pg_sleep(0.4);
  if not exists (select 1 from public.profiles_auth
                 where profile_id = p_profile_id and pass_hash = p_hash) then
    return null;
  end if;
  delete from public.sessions
   where profile_id = p_profile_id
     and token not in (select token from public.sessions
                        where profile_id = p_profile_id order by last_seen desc limit 4);
  tok := encode(extensions.gen_random_bytes(32), 'hex');
  insert into public.sessions(token, profile_id) values (tok, p_profile_id);
  return tok;
end $$;

create or replace function public.auth_verify(p_profile_id uuid, p_hash text)
returns boolean language plpgsql security definer set search_path to 'public' as $$
begin
  perform pg_sleep(0.4);
  return exists (select 1 from public.profiles_auth
                 where profile_id = p_profile_id and pass_hash = p_hash);
end $$;

create or replace function public.auth_register(p_profile_id uuid, p_hash text)
returns text language plpgsql security definer set search_path to 'public' as $$
declare tok text;
begin
  if exists (select 1 from public.profiles_auth where profile_id = p_profile_id) then
    raise exception 'credencial já existe';
  end if;
  insert into public.profiles_auth(profile_id, pass_hash) values (p_profile_id, p_hash);
  tok := encode(extensions.gen_random_bytes(32), 'hex');
  insert into public.sessions(token, profile_id) values (tok, p_profile_id);
  return tok;
end $$;

create or replace function public.auth_logout(p_token text)
returns void language sql security definer set search_path to 'public' as $$
  delete from public.sessions where token = p_token
$$;

create or replace function public.password_change(p_token text, p_old_hash text, p_new_hash text)
returns boolean language plpgsql security definer set search_path to 'public' as $$
declare uid uuid; rec record;
begin
  uid := public.session_owner(p_token);
  if uid is null then raise exception 'sessão inválida'; end if;
  if p_new_hash is null or length(p_new_hash) < 32 then raise exception 'password inválida'; end if;

  select pass_hash, must_change into rec from public.profiles_auth where profile_id = uid;
  if not coalesce(rec.must_change, false) then
    perform pg_sleep(0.3);
    if rec.pass_hash is distinct from p_old_hash then return false; end if;
  end if;

  update public.profiles_auth
     set pass_hash = p_new_hash, must_change = false, temp_expires = null, updated_at = now()
   where profile_id = uid;

  delete from public.sessions where profile_id = uid and token <> p_token;
  return true;
end $$;

create or replace function public.password_admin_reset(p_target_id uuid, p_temp_hash text, p_token text)
returns boolean language plpgsql security definer set search_path to 'public' as $$
declare caller uuid;
begin
  caller := public.session_owner(p_token);
  if caller is null then raise exception 'sessão inválida'; end if;
  if not public.is_admin(caller) then return false; end if;
  update public.profiles_auth
     set pass_hash = p_temp_hash, must_change = true, temp_expires = now() + interval '24 hours'
   where profile_id = p_target_id;
  delete from public.sessions where profile_id = p_target_id;
  return true;
end $$;

-- ── Perfil ───────────────────────────────────────────────────────────────────
create or replace function public.profile_update(p_token text, p_display_name text default null,
                                                  p_photo text default null, p_clear_photo boolean default false)
returns boolean language plpgsql security definer set search_path to 'public' as $$
declare uid uuid;
begin
  uid := public.session_owner(p_token);
  if uid is null then raise exception 'sessão inválida'; end if;
  if p_photo is not null and char_length(p_photo) > 700000 then
    raise exception 'foto demasiado grande'; end if;
  update public.profiles set
    display_name = coalesce(p_display_name, display_name),
    photo_url = case when p_clear_photo then null else coalesce(p_photo, photo_url) end
  where id = uid;
  return found;
end $$;

-- ── Edições ──────────────────────────────────────────────────────────────────
create or replace function public.edition_merge_field(edition_id uuid, field_name text, delta jsonb,
                                                       p_token text default null)
returns jsonb language plpgsql security definer set search_path to 'public' as $$
declare uid uuid; result jsonb; adm boolean;
begin
  uid := public.session_owner(p_token);
  if uid is null then raise exception 'sessão inválida'; end if;
  adm := public.is_admin(uid);
  if not adm and not public._edition_can_write(uid, field_name) then
    raise exception 'sem permissão para escrever em %', field_name;
  end if;
  update public.editions
     set data = jsonb_set(coalesce(data,'{}'::jsonb), array[field_name],
                          coalesce(data->field_name,'{}'::jsonb) || delta, true)
   where id = edition_id
   returning data into result;
  return result;
end $$;

create or replace function public.edition_append_array(edition_id uuid, field_name text, item jsonb,
                                                        p_token text default null)
returns jsonb language plpgsql security definer set search_path to 'public' as $$
declare uid uuid; result jsonb; current_arr jsonb; item_id text;
begin
  uid := public.session_owner(p_token);
  if uid is null then raise exception 'sessão inválida'; end if;
  if not public.is_admin(uid) and not public._edition_can_write(uid, field_name) then
    raise exception 'sem permissão'; end if;

  select coalesce(data->field_name, '[]'::jsonb) into current_arr
    from public.editions where id = edition_id;
  item_id := item->>'id';
  if item_id is not null and exists (
    select 1 from jsonb_array_elements(current_arr) elem where elem->>'id' = item_id
  ) then
    select data into result from public.editions where id = edition_id;
    return result;
  end if;
  update public.editions
     set data = jsonb_set(coalesce(data,'{}'::jsonb), array[field_name],
                          current_arr || jsonb_build_array(item), true)
   where id = edition_id
   returning data into result;
  return result;
end $$;

create or replace function public.edition_remove_from_array(edition_id uuid, field_name text, item_id text,
                                                            p_token text default null)
returns jsonb language plpgsql security definer set search_path to 'public' as $$
declare uid uuid; result jsonb; current_arr jsonb; filtered jsonb; owner text;
begin
  uid := public.session_owner(p_token);
  if uid is null then raise exception 'sessão inválida'; end if;

  select coalesce(data->field_name, '[]'::jsonb) into current_arr
    from public.editions where id = edition_id;

  select elem->>'by' into owner
    from jsonb_array_elements(current_arr) elem where elem->>'id' = item_id limit 1;
  if not public.is_admin(uid) and owner is distinct from uid::text then
    raise exception 'só podes remover o que é teu';
  end if;

  select coalesce(jsonb_agg(elem), '[]'::jsonb) into filtered
    from jsonb_array_elements(current_arr) elem
   where elem->>'id' is null or elem->>'id' <> item_id;

  update public.editions
     set data = jsonb_set(coalesce(data,'{}'::jsonb), array[field_name], filtered, true)
   where id = edition_id
   returning data into result;
  return result;
end $$;

create or replace function public.edition_write(p_token text, p_edition_id uuid, p_data jsonb default null,
                                                p_phase integer default null, p_status text default null,
                                                p_number integer default null, p_title text default null,
                                                p_subtitle text default null)
returns boolean language plpgsql security definer set search_path to 'public' as $$
declare uid uuid; adm boolean;
begin
  uid := public.session_owner(p_token);
  if uid is null then raise exception 'sessão inválida'; end if;
  adm := public.is_admin(uid);
  if not adm and (p_phase is not null or p_status is not null
                  or p_number is not null or p_title is not null or p_subtitle is not null) then
    raise exception 'só o admin muda a fase, o estado ou o nome';
  end if;
  update public.editions set
    data          = coalesce(p_data, data),
    current_phase = coalesce(p_phase, current_phase),
    status        = coalesce(p_status, status),
    number        = coalesce(p_number, number),
    title         = coalesce(p_title, title),
    subtitle      = coalesce(p_subtitle, subtitle)
  where id = p_edition_id;
  return found;
end $$;

create or replace function public.edition_create(p_token text, p_number integer, p_title text,
                                                 p_subtitle text, p_status text, p_data jsonb)
returns public.editions language plpgsql security definer set search_path to 'public' as $$
declare uid uuid; row public.editions;
begin
  uid := public.session_owner(p_token);
  if uid is null then raise exception 'sessão inválida'; end if;
  if p_status <> 'proposed' and not public.is_admin(uid) then
    raise exception 'só o admin cria aventuras'; end if;
  insert into public.editions(number, title, subtitle, status, current_phase, data)
  values (coalesce(p_number,0), coalesce(p_title,'Nova Aventura'),
          coalesce(p_subtitle,''), coalesce(p_status,'active'), 1, coalesce(p_data,'{}'::jsonb))
  returning * into row;
  return row;
end $$;

create or replace function public.edition_delete(p_edition_id uuid, p_token text)
returns boolean language plpgsql security definer set search_path to 'public' as $$
declare uid uuid;
begin
  uid := public.session_owner(p_token);
  if uid is null then raise exception 'sessão inválida'; end if;
  if not public.is_admin(uid) then return false; end if;
  delete from public.editions where id = p_edition_id;
  return true;
end $$;

-- ── Chat ─────────────────────────────────────────────────────────────────────
create or replace function public.chat_send(p_token text, p_text text)
returns public.chat_messages language plpgsql security definer set search_path to 'public' as $$
declare uid uuid; row public.chat_messages; recent int;
begin
  uid := public.session_owner(p_token);
  if uid is null then raise exception 'sessão inválida'; end if;
  if p_text is null or char_length(btrim(p_text)) = 0 or char_length(p_text) > 2000 then
    raise exception 'mensagem inválida'; end if;
  select count(*) into recent from public.chat_messages
   where profile_id = uid and created_at > now() - interval '1 minute';
  if recent >= 20 then raise exception 'demasiadas mensagens — abranda um pouco'; end if;

  insert into public.chat_messages(profile_id, text) values (uid, p_text) returning * into row;
  return row;
end $$;

create or replace function public.chat_delete(p_message_id bigint, p_token text)
returns boolean language plpgsql security definer set search_path to 'public' as $$
declare uid uuid; owner uuid;
begin
  uid := public.session_owner(p_token);
  if uid is null then raise exception 'sessão inválida'; end if;
  select profile_id into owner from public.chat_messages where id = p_message_id;
  if owner is distinct from uid and not public.is_admin(uid) then return false; end if;
  delete from public.chat_messages where id = p_message_id;
  return true;
end $$;

-- ── Bug reports ──────────────────────────────────────────────────────────────
create or replace function public.bug_report_send(p_token text, p_description text, p_image text default null)
returns boolean language plpgsql security definer set search_path to 'public' as $$
declare uid uuid; nome text; recent int;
begin
  uid := public.session_owner(p_token);
  if uid is null then raise exception 'sessão inválida'; end if;
  if char_length(coalesce(p_description,'')) not between 1 and 800 then
    raise exception 'descrição inválida'; end if;
  if p_image is not null and char_length(p_image) > 500000 then
    raise exception 'imagem demasiado grande'; end if;
  select count(*) into recent from public.bug_reports
   where by_id = uid::text and created_at > now() - interval '1 hour';
  if recent >= 5 then raise exception 'demasiados reports — tenta daqui a bocado'; end if;

  select coalesce(display_name, name) into nome from public.profiles where id = uid;
  insert into public.bug_reports(by_id, by_name, description, image)
  values (uid::text, nome, p_description, p_image);
  return true;
end $$;

create or replace function public.bug_reports_list(p_token text)
returns setof public.bug_reports language plpgsql security definer set search_path to 'public' as $$
declare uid uuid;
begin
  uid := public.session_owner(p_token);
  if uid is null or not public.is_admin(uid) then return; end if;
  return query select * from public.bug_reports order by created_at desc;
end $$;

create or replace function public.bug_reports_clear(p_token text, p_report_id uuid default null)
returns integer language plpgsql security definer set search_path to 'public' as $$
declare uid uuid; n integer;
begin
  uid := public.session_owner(p_token);
  if uid is null then raise exception 'sessão inválida'; end if;
  if not public.is_admin(uid) then return -1; end if;
  if p_report_id is null then delete from public.bug_reports; get diagnostics n = row_count;
  else delete from public.bug_reports where id = p_report_id; get diagnostics n = row_count; end if;
  return n;
end $$;

-- ============================================================================
-- Fim. Fontes: funções e políticas exatas do dump da base (2026-07);
-- tabelas reconstruídas do uso nas funções. A base viva é a fonte da verdade.
-- ============================================================================
